---
- hosts: all
  become: yes
  vars_files:
    - vars/secure.yml

  pre_tasks:
    - name: Install fail2ban
      ansible.builtin.apt:
        name: fail2ban
        state: present
      become: yes

  tasks:
    - block:
        - name: Execute security role
          include_role:
            name: geerlingguy.security
          become: yes