---
- hosts: all
  vars_files:
    - vars/secure.yml

  pre_tasks:
    - name: Print current user
      command: whoami
      register: whoami
    - debug:
        var: whoami.stdout

    - name: Install fail2ban
      ansible.builtin.apt:
        name: fail2ban
        state: present

  tasks:
    - block:
        - name: Execute security role
          include_role:
            name: geerlingguy.security