---
- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/secure.yml

  pre_tasks:
    - name: Print current user
      command: whoami
      register: whoami
      become: yes
    - debug:
        var: whoami.stdout

    - name: Ensure a line is present in sudoers
      lineinfile:
        path: /etc/sudoers
        insertafter: EOF
        line: 'rustic ALL=(ALL) NOPASSWD: ALL'
      become: yes
      become_user: root

  tasks:
    - block:
        - name: Execute security role
          include_role:
            name: geerlingguy.security
      become: yes
